// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	DeleteOrder(ctx context.Context, id pgtype.UUID) error
	DeleteTicket(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItemByID(ctx context.Context, id pgtype.UUID) (OrderItem, error)
	GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	ListTicketsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Ticket, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateTicketStock(ctx context.Context, arg UpdateTicketStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
