// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    event_id, name, price, total_quantity
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, event_id, name, price, total_quantity, created_at, updated_at
`

type CreateTicketParams struct {
	EventID       pgtype.UUID    `json:"event_id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	TotalQuantity int32          `json:"total_quantity"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.EventID,
		arg.Name,
		arg.Price,
		arg.TotalQuantity,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, event_id, name, price, total_quantity, created_at, updated_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByEvent = `-- name: ListTicketsByEvent :many
SELECT id, event_id, name, price, total_quantity, created_at, updated_at
FROM tickets
WHERE event_id = $1
ORDER BY price ASC
`

func (q *Queries) ListTicketsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.TotalQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET 
    name = $2,
    price = $3,
    total_quantity = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, event_id, name, price, total_quantity, created_at, updated_at
`

type UpdateTicketParams struct {
	ID            pgtype.UUID    `json:"id"`
	Name          string         `json:"name"`
	Price         pgtype.Numeric `json:"price"`
	TotalQuantity int32          `json:"total_quantity"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.TotalQuantity,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.TotalQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketStock = `-- name: UpdateTicketStock :exec
UPDATE tickets
SET total_quantity = total_quantity - $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTicketStockParams struct {
	ID            pgtype.UUID `json:"id"`
	TotalQuantity int32       `json:"total_quantity"`
}

func (q *Queries) UpdateTicketStock(ctx context.Context, arg UpdateTicketStockParams) error {
	_, err := q.db.Exec(ctx, updateTicketStock, arg.ID, arg.TotalQuantity)
	return err
}
